"""
Data Models for ETSI AI-Agents Use Case Processing

Defines Pydantic models for:
1. Document chunks (for RAG retrieval)
2. Agent outputs (UseCaseSummary)
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


# =============================================================================
# Enums
# =============================================================================

class UseCaseCategory(str, Enum):
    """
    Categories based on ETSI document structure:
    - Section 5.1.x = Consumer
    - Section 5.2.x = Business
    - Section 5.3.x = Operator
    """
    CONSUMER = "consumer"
    BUSINESS = "business"
    OPERATOR = "operator"


class SectionType(str, Enum):
    """Types of content within each use case."""
    DESCRIPTION = "description"
    REQUIREMENTS = "requirements"


# =============================================================================
# Document Chunk Model (for RAG)
# =============================================================================

class DocumentChunk(BaseModel):
    """
    A chunk ready for embedding and vector storage.
    
    This is the core model for RAG retrieval.
    """
    chunk_id: str = Field(
        ...,
        description="Unique chunk identifier"
    )
    content: str = Field(
        ...,
        description="Text content to be embedded"
    )
    use_case_id: str = Field(
        ...,
        description="Parent use case: 5.1.1, 5.2.1, etc."
    )
    use_case_name: str = Field(
        ...,
        description="Parent use case title"
    )
    section_type: SectionType = Field(
        ...,
        description="DESCRIPTION or REQUIREMENTS"
    )
    category: UseCaseCategory = Field(
        ...,
        description="Consumer, Business, or Operator"
    )
    page_start: int = Field(
        ...,
        description="Page where this chunk appears"
    )
    token_count: int = Field(
        default=0,
        description="Approximate token count"
    )
    chunk_index: int = Field(
        ...,
        description="Position in document for ordering"
    )


# =============================================================================
# Agent Output Models (for Phase 2)
# =============================================================================

class ServiceFlowStep(BaseModel):
    """A single step in the use case service flow."""
    step_number: int = Field(
        ...,
        description="Step number: 1, 2, 3, etc."
    )
    description: str = Field(
        ...,
        description="What happens in this step"
    )
    actors_involved: list[str] = Field(
        default_factory=list,
        description="Actors participating in this step"
    )


class UseCaseSummary(BaseModel):
    """
    Structured summary generated by the Summarizer Agent.
    
    This schema forces the LLM to extract specific information
    in a consistent format.
    """
    use_case_id: str = Field(
        ...,
        description="Use case ID: 5.1.1, 5.2.1, etc."
    )
    title: str = Field(
        ...,
        description="Use case title"
    )
    category: UseCaseCategory = Field(
        ...,
        description="Consumer, Business, or Operator"
    )
    
    # Actors and entities
    actors: list[str] = Field(
        ...,
        description="All actors: User, Robot, AI Agent, etc."
    )
    network_functions: list[str] = Field(
        default_factory=list,
        description="5G/6G functions: AMF, SMF, PCF, UPF, etc."
    )
    
    # Summary
    description: str = Field(
        ...,
        description="2-3 sentence summary of the use case"
    )
    problem_solved: str = Field(
        default="",
        description="What problem does this use case address?"
    )
    
    # Service flow
    service_flow: list[ServiceFlowStep] = Field(
        default_factory=list,
        description="Numbered steps from the service flow"
    )
    
    # Requirements
    requirement_ids: list[str] = Field(
        default_factory=list,
        description="List of requirement IDs: [PR 5.1.1-1, ...]"
    )
    
    # Metadata
    source_pages: list[int] = Field(
        default_factory=list,
        description="Pages where this use case appears"
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When this summary was generated"
    )


# =============================================================================
# Helper Functions
# =============================================================================

def get_use_case_category(use_case_id: str) -> UseCaseCategory:
    """
    Determine category from use case ID.
    
    - 5.1.x -> Consumer
    - 5.2.x -> Business
    - 5.3.x -> Operator
    """
    if use_case_id.startswith("5.1"):
        return UseCaseCategory.CONSUMER
    elif use_case_id.startswith("5.2"):
        return UseCaseCategory.BUSINESS
    elif use_case_id.startswith("5.3"):
        return UseCaseCategory.OPERATOR
    else:
        raise ValueError(f"Unknown category for use case: {use_case_id}")


def get_parent_id(section_id: str) -> Optional[str]:
    """
    Get parent section ID by removing last level.
    
    Examples:
        get_parent_id("5.1.1.1") -> "5.1.1"
        get_parent_id("5.1.1") -> "5.1"
        get_parent_id("5") -> None
    """
    parts = section_id.split(".")
    if len(parts) <= 1:
        return None
    return ".".join(parts[:-1])